### ISSUE TITLE
Provide a single minified JS file

### ISSUE THREAD

**Issue by matthiasschaub** [devloop01/vecteur#14]
Thanks for providing this awesome and small library! I stumbled upon this library through this code-pen: https://codepen.io/dev_loop/pen/abxJMxL

I would love to use it by just downloading a single minified JS file instead of using NPM & co to install it.

A single minified JS file is one of the easiest options to use a library in a self-hosted setting → Just load it into a web page in a script tag.

It would be great if you could provide such a file.

Thanks a lot.

**Comment by devloop01** [comment]
Yeah but with a bundler like Vite or Webpack you would get better code modification / code splitting.

But I'll look into it if I can change the `rollup` config and export a single final minified build.

**Comment by devloop01** [comment]
#15 this pr adds the single minified build to npm. you can use sources like `unpkg` to get the minified file.

here's the link if you need it https://unpkg.com/vecteur@0.3.0/dist/vecteur.min.js

**Comment by matthiasschaub** [comment]
Cool, that was fast. Thanks a lot! And I definitely will reference your library.
